platform :ios, '8.0'

inhibit_all_warnings!

target 'MVVMReactiveCocoaExample' do
    pod 'MJRefresh', '~> 3.1.12'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'Masonry', '~> 1.0.2'
    pod 'MJExtension', '~> 3.0.13'
    pod 'Reachability', '~> 3.2'
    pod 'SDWebImage', '~> 4.0.0'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'ReactiveCocoa', '~> 2.5'
    pod 'FDFullscreenPopGesture', '1.1'
    pod 'MLeaksFinder'
    
    
end
